# Generated by Django 4.2.3 on 2023-07-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
